language: rust

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.7
      - python3-pip
cache:
  - cargo
  - pip

before_install:
  - python3.7 --version
  - python3.7 -m pip install pip --user
  - pip install --upgrade setuptools pip --user
  - pip install pre-commit --user
  - rustup component add clippy
  - rustup component add rustfmt

before_script:
  - pre-commit run --all-files

script:
  - cd nova-luna-solver
  - cargo build --verbose; cargo test --verbose
