language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

before_install:
  - pip install pre-commit --user
  - rustup component add clippy
  - rustup component add rustfmt

before_script:
  - pre-commit run --all-files
