language: rust

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.7
      - python3-pip
cache:
  - cargo
  - pip

before_install:
  - python3.7 --version
  - pip3.7 install --upgrade setuptools pip --user
  - pip3.7 install pre-commit --user
  - rustup component add clippy
  - rustup component add rustfmt

before_script:
  - pre-commit run --all-files
